version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=express-api
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  app:
    build: 
      context: ./express-api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
       - ./express-api:/app
    depends_on:
      - db
    environment:
      - POSTGRES_DB=express-api
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
  
  
  #scraper:
  #  build:
  #    context: ./scraper
  #    dockerfile: Dockerfile
  #  depends_on:
  #    - app
  #client:
  #  build: ./client
  #  ports:
  #    - '8080:8080'
  #  volumes:
  #    - ./client:/app
  #  depends_on:
  #    - app
  #    - scraper
