version: '3'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=express-api
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  app:
    build: 
      context: ./express-api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - POSTGRES_DB=express-api
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - app

